# This file was generated by GoReleaser. DO NOT EDIT.
class Jwkgen < Formula
  desc "Small command-line tool that generates asymmetric JSON Web Keys for the
following algorithms and curves
"
  homepage "https://github.com/rakutentech/jwkgen"
  version "1.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rakutentech/jwkgen/releases/download/v1.4.2/jwkgen-darwin-x86_64.tar.gz"
    sha256 "f1859a973238467546152d876a508e2bacc669a920281ab6618aa8c1961b31fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rakutentech/jwkgen/releases/download/v1.4.2/jwkgen-linux-x86_64.tar.gz"
      sha256 "4f6bd1673b65a42e7759e28dcf0941c80a19a2edd498badfbd4a70ecd51cee7f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rakutentech/jwkgen/releases/download/v1.4.2/jwkgen-linux-arm64.tar.gz"
        sha256 "700d25e22f764c7382c26c73de18cb60e360e61af9b2154021b29f86ce8102c4"
      else
        url "https://github.com/rakutentech/jwkgen/releases/download/v1.4.2/jwkgen-linux-armv6.tar.gz"
        sha256 "adb2d87656ea81595625006e28ede3dc6ac373d947f177b22cb49c2078bcdcba"
      end
    end
  end

  def install
    bin.install "jwkgen"
  end
end
